language: node_js
node_js: stable
# 指定需要sudo权限
sudo: required
# 指定node_js版本
node_js: 
  - 8.0.0
# 缓存，可以节省集成的时间，这里我用了yarn，如果不用可以删除
cache:
  apt: true
  yarn: true
  directories:
    - node_modules
# S: Build Lifecycle
before_install:
  - npm install -g hexo-cli
install:
  - npm install
  # - npm install safe-buffer --save
  # - npm install strip-ansi --save
  # - npm install ansi-regex --save
  # - npm install wrappy --save
  # - npm install yallist --save

#before_script:
 # - npm install -g gulp

script:
  # - yuque-hexo sync
  - hexo clean
  - hexo g

after_script:
  - npm ls --depth 0
  - cd ./public
  - git init
  - git config user.name "shiwentao666"
  - git config user.email "shiwentao666@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - source_code
env:
 global:
   - GH_REF: github.com/hienao/hienao.github.io.git --{仓库地址}