language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install
  - npm i -g yuque-hexo

#before_script:
 # - npm install -g gulp

script:
  - yuque-hexo sync
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "shiwentao666"
  - git config user.email "shiwentao666@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/hienao/hienao.github.io.git --{仓库地址}